# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events to main, dev-v, or dev branches
  push:
    branches: [ "main", "dev-v", "dev" ]
  pull_request:
    branches: [ "main", "dev-v", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Make the script executable (in case it's not already)
      - name: Make script executable
        run: chmod +x run_tests.sh

      # Runs a single command using the runners shell
      - name: Run tests script
        run: ./run_tests.sh